### ISSUE TITLE
No files generated?

### ISSUE THREAD

**Issue by joshualerickson** [leonawicz/tiler#17]
Looks like a sweet package and would love to get working on my computer. If you wouldn't mind taking a look and seeing what might be going on that would be much appreciated. Below is the reprex. What I noticed when running is the .html file is blank when viewed online (boundary will appear as layerControl and a point marker in the lower right corner) and no files are generated into either the temp directory or even when trying another directory. I've tried running the `gdal2tiles.py` on OSgeo Shell but get an error. Don't know if these are related or not... Thanks for your time.

``` r
library(tiler)
library(raster)
#> Loading required package: sp
tiler_options(osgeo4w = "C:/OSGeo4W64/OSGeo4W.bat", python = "C:/Python/ArcGIS10.5/python.exe")

tiles <- file.path(tempdir(), "tiles")
x <- system.file("maps/map_wgs84.tif", package = "tiler")

tile(x, tiles, zoom = '2-3')
#> Reprojecting raster...
#> Warning in raster::projectRaster(r, e, method = method): input and ouput crs are
#> the same
#> Coloring raster...
#> Preparing for tiling...
#> [1] "C:\\Users\\JOSHUA~1\\AppData\\Local\\Temp\\RtmpozBdUM"
#> Creating tiles. Please wait...
#> Creating tile viewer...
#> Complete.
view_tiles(file.path(tempdir(), "tiles"))
```

<sup>Created on 2020-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Error from OSGeo4W Shell

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\GDAL\gdal2tiles.py", line 44, in <module>
    from osgeo import gdal
  File "C:\Python27\ArcGIS10.5\lib\site-packages\osgeo\__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "C:\Python27\ArcGIS10.5\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by joshualerickson** [comment]
Had a 64-bit OSGeo4W.bat file trying to work with 32-bit python. Sorry for the frustration post, need to be more patient.
